name: Url Health Check

on:
  schedule:
    - cron: '30 8,20 * * *'

jobs:
  url_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check service health 
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-pv0b.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
          follow-redirect: true

      - name: Notify success on Discord
        if: ${{ success() }}
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            "✅ Health check was OK!"
      - name: Notify failure on Discord
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            "❌ Health check failed."
